apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sftp-server.fullname" . }}
  labels:
    {{- include "sftp-server.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.sftp.password | b64enc }}