apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sftp-server.fullname" . }}
  labels:
    {{- include "sftp-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azure-file-share
  resources:
    requests:
      storage: 5Gi