apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret
  namespace: nginx-ingress
spec:
  secretName: tls-secret
  dnsNames:
  - erikcloud.ddns.net
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - erikcloud.ddns.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer