# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az group create -n "$GITHUB_HEAD_REF"EjaSentia -l westeurope
            az deployment group create --name "$GITHUB_HEAD_REF"EjaSentia --resource-group "$GITHUB_HEAD_REF"EjaSentia --template-file ./arm_templates/azuredeploy.json --parameters ./azuredeploy.parameters.json --parameters environment=$GITHUB_HEAD_REF