# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      LOCATION: westeurope
      RESOURCE_GROUP: testEjaSentia
      AKS_CLUSTER_NAME: ejaSentia

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: debug
        run: |
          ls -la ./arm_templates/azuredeploy.json

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Create resource group
      #   uses: azure/CLI@v1
      #   with:
      #     azcliversion: 2.0.72
      #     inlineScript: |
      #       az group create --name ${{ env.RESOURCE_GROUP }} --location ${{ env.LOCATION }}
      
      # - uses: azure/arm-deploy@v1
      #   with:
      #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
      #     resourceGroupName: ${{ env.RESOURCE_GROUP }}
      #     template: ./arm_templates/azuredeploy.json
      #     parameters: environment=test existingServicePrincipalClientId=4b6c8589-dc81-4229-af9b-cb031124e212 existingServicePrincipalClientSecret=${{ secrets.AKS_SP_SECRET }}

      - name: Create resource group
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            echo "PUBLIC_IP_ADDRESS=$(az network public-ip create --resource-group MC_${{ env.RESOURCE_GROUP }}_${{ env.AKS_CLUSTER_NAME }}_${{ env.LOCATION }} --name testPublicIp --sku Standard --allocation-method static --query publicIp.ipAddress -o tsv)" >> $PUBLIC_IP_ADDRESS
